platform: linux
image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
inputs:
- name: deploy-kops.git
run:
  path: deploy-kops.git/ci/scripts/deploy.sh
  args: []
outputs: []
params:
  ENV_NAME:
  JUMPBOX_SSH_PORT:
  JUMPBOX_SSH_KEY:
  SSH_CA:
