---
resources:
- name: deploy-kops.git
  type: git
  source:
    branch: master
    private_key: {{deploy_kops_git_deploy_key}}
    uri: git@github.com:govau/deploy-kops.git
jobs:
- name: deploy-k
  plan:
  - do:
    - aggregate:
      - get: deploy-kops.git
        trigger: true
    - task: deploy
      file: deploy-kops.git/ci/tasks/deploy.yml
      params:
        ENV_NAME: k
        JUMPBOX_SSH_PORT: {{jumpbox_ssh_port}}
        JUMPBOX_SSH_KEY: {{jumpbox_ssh_key}}
        SSH_CA: {{ssh_ca}}
